version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./:/srv/app:rw
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
    environment:
      APP_ENV: dev
      MAILER_DSN: smtp://maildev:25

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      # HTTP
      - target: 80
        published: 8080
        protocol: tcp
      # HTTPS
      - target: 443
        published: 8443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 8443
        protocol: udp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8081:80
    environment:
      - PMA_HOST=database

  maildev:
    image: maildev/maildev:latest
    restart: unless-stopped
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 8082:80
