version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./:/srv/app:rw
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
    environment:
      APP_ENV: dev

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro
    ports:
      # HTTP
      - target: 80
        published: 8080
        protocol: tcp
      # HTTPS
      - target: 443
        published: 8443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 8443
        protocol: udp
