version: "3.4"

services:
###> php app ###
  php:
    build:
      context: .
      target: symfony_php
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - php_socket:/var/run/php
      - public_dir:/srv/app/public
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.7.4
      MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
      MAILER_DSN: smtp://localhost:25
      ADMIN_EMAIL: ${ADMIN_ACCOUNT_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_ACCOUNT_PASSWORD}
###< php app ###

###> caddy ###
  caddy:
    build:
      context: .
      target: symfony_caddy
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - public_dir:/srv/app/public
    ports:
      - "80:80/tcp"   # HTTP
      - "443:443/tcp" # HTTPS
      - "443:443/udp" # HTTP/3
###< caddy ###

###> mariadb ###
  database:
    image: mariadb:10.7.4
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
###< mariadb ###

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  mariadb_data:
  public_dir:
